export const quizSentences = [
    {
      sentence: "____, wie geht's?",
      translation: "สวัสดี",
      correctAnswer: "Hallo",
      options: ["Hallo", "Tschüss", "Ja", "Danke"],
    },
    {
      sentence: "____ für deine Hilfe.",
      translation: "ขอบคุณ",
      correctAnswer: "Danke",
      options: ["Danke", "Wasser", "Freund", "Schule"],
    },
    {
      sentence: "____, ich verstehe.",
      translation: "ใช่",
      correctAnswer: "Ja",
      options: ["Nein", "Ja", "Tschüss", "Gute Nacht"],
    },
    {
      sentence: "____, das ist nicht richtig.",
      translation: "ไม่",
      correctAnswer: "Nein",
      options: ["Ja", "Entschuldigung", "Nein", "Tschüss"],
    },
    {
      sentence: "____, wo ist der Bahnhof?",
      translation: "ขอโทษ",
      correctAnswer: "Entschuldigung",
      options: ["Entschuldigung", "Freund", "Tschüss", "Arbeit"],
    },
    {
      sentence: "____ Morgen! Wie geht's?",
      translation: "สวัสดีตอนเช้า",
      correctAnswer: "Guten Morgen",
      options: ["Guten Morgen", "Tschüss", "Freund", "Essen"],
    },
    {
      sentence: "____, träum schön!",
      translation: "ราตรีสวัสดิ์",
      correctAnswer: "Gute Nacht",
      options: ["Tschüss", "Gute Nacht", "Wasser", "Freund"],
    },
    {
      sentence: "____, bis später!",
      translation: "บ๊ายบาย",
      correctAnswer: "Tschüss",
      options: ["Tschüss", "Ja", "Arbeit", "Haus"],
    },
    {
      sentence: "____ kostet das?",
      translation: "เท่าไหร่?",
      correctAnswer: "Wie viel?",
      options: ["Wie viel?", "Arbeit", "Freund", "Haus"],
    },
    {
      sentence: "Ich trinke ____.",
      translation: "น้ำ",
      correctAnswer: "Wasser",
      options: ["Freund", "Wasser", "Arbeit", "Katze"],
    },
    {
      sentence: "Er ist mein bester ____.",
      translation: "เพื่อน",
      correctAnswer: "Freund",
      options: ["Freund", "Auto", "Buch", "Essen"],
    },
    {
      sentence: "Ich habe Hunger, lass uns ____ gehen.",
      translation: "กิน",
      correctAnswer: "Essen",
      options: ["Essen", "Auto", "Buch", "Schule"],
    },
    {
      sentence: "Ich wohne in einem großen ____.",
      translation: "บ้าน",
      correctAnswer: "Haus",
      options: ["Haus", "Arbeit", "Buch", "Hund"],
    },
    {
      sentence: "Ich muss morgen ____.",
      translation: "ทำงาน",
      correctAnswer: "Arbeit",
      options: ["Schule", "Arbeit", "Haus", "Katze"],
    },
    {
      sentence: "Die ____ beginnt um 8 Uhr.",
      translation: "โรงเรียน",
      correctAnswer: "Schule",
      options: ["Schule", "Freund", "Wasser", "Buch"],
    },
    {
      sentence: "Ich lese ein interessantes ____.",
      translation: "หนังสือ",
      correctAnswer: "Buch",
      options: ["Buch", "Auto", "Haus", "Freund"],
    },
    {
      sentence: "Mein ____ ist blau.",
      translation: "รถ",
      correctAnswer: "Auto",
      options: ["Auto", "Hund", "Haus", "Katze"],
    },
    {
      sentence: "Der ____ läuft im Park.",
      translation: "สุนัข",
      correctAnswer: "Hund",
      options: ["Hund", "Katze", "Freund", "Arbeit"],
    },
    {
      sentence: "Die ____ schläft auf dem Sofa.",
      translation: "แมว",
      correctAnswer: "Katze",
      options: ["Katze", "Freund", "Essen", "Haus"],
    },
    {
      sentence: "Ich empfinde große ____.",
      translation: "ความสุข",
      correctAnswer: "Freude",
      options: ["Freude", "Buch", "Arbeit", "Schule"],
    },
  ];