export const germanWords = [
  {
    word: "Hallo",
    example: "Hallo, wie geht's?",
    translation: "สวัสดี",
    sentenceTranslation: "สวัสดี, สบายดีไหม?",
  },
  {
    word: "Danke",
    example: "Danke für deine Hilfe.",
    translation: "ขอบคุณ",
    sentenceTranslation: "ขอบคุณสำหรับความช่วยเหลือของคุณ",
  },
  {
    word: "Ja",
    example: "Ja, ich verstehe.",
    translation: "ใช่",
    sentenceTranslation: "ใช่, ฉันเข้าใจ",
  },
  {
    word: "Nein",
    example: "Nein, das ist nicht richtig.",
    translation: "ไม่",
    sentenceTranslation: "ไม่, นั่นไม่ถูกต้อง",
  },
  {
    word: "Entschuldigung",
    example: "Entschuldigung, wo ist der Bahnhof?",
    translation: "ขอโทษ",
    sentenceTranslation: "ขอโทษ, สถานีรถไฟอยู่ที่ไหน?",
  },
  {
    word: "Guten Morgen",
    example: "Guten Morgen! Wie geht's?",
    translation: "สวัสดีตอนเช้า",
    sentenceTranslation: "สวัสดีตอนเช้า! สบายดีไหม?",
  },
  {
    word: "Gute Nacht",
    example: "Gute Nacht, träum schön!",
    translation: "ราตรีสวัสดิ์",
    sentenceTranslation: "ราตรีสวัสดิ์, ฝันดี!",
  },
  {
    word: "Tschüss",
    example: "Tschüss, bis später!",
    translation: "บ๊ายบาย",
    sentenceTranslation: "บ๊ายบาย, แล้วเจอกันใหม่!",
  },
  {
    word: "Wie viel?",
    example: "Wie viel kostet das?",
    translation: "เท่าไหร่?",
    sentenceTranslation: "มันราคาเท่าไหร่?",
  },
  {
    word: "Wasser",
    example: "Ich trinke Wasser.",
    translation: "น้ำ",
    sentenceTranslation: "ฉันดื่มน้ำ",
  },
  {
    word: "Freund",
    example: "Er ist mein bester Freund.",
    translation: "เพื่อน",
    sentenceTranslation: "เขาคือเพื่อนที่ดีที่สุดของฉัน",
  },
  {
    word: "Essen",
    example: "Ich habe Hunger, lass uns essen gehen.",
    translation: "กิน",
    sentenceTranslation: "ฉันหิว, ไปกินข้าวกันเถอะ",
  },
  {
    word: "Haus",
    example: "Ich wohne in einem großen Haus.",
    translation: "บ้าน",
    sentenceTranslation: "ฉันอาศัยอยู่ในบ้านหลังใหญ่",
  },
  {
    word: "Arbeit",
    example: "Ich muss morgen arbeiten.",
    translation: "ทำงาน",
    sentenceTranslation: "ฉันต้องทำงานพรุ่งนี้",
  },
  {
    word: "Schule",
    example: "Die Schule beginnt um 8 Uhr.",
    translation: "โรงเรียน",
    sentenceTranslation: "โรงเรียนเริ่มตอน 8 โมง",
  },
  {
    word: "Buch",
    example: "Ich lese ein interessantes Buch.",
    translation: "หนังสือ",
    sentenceTranslation: "ฉันอ่านหนังสือที่น่าสนใจ",
  },
  {
    word: "Auto",
    example: "Mein Auto ist blau.",
    translation: "รถ",
    sentenceTranslation: "รถของฉันสีน้ำเงิน",
  },
  {
    word: "Hund",
    example: "Der Hund läuft im Park.",
    translation: "สุนัข",
    sentenceTranslation: "สุนัขวิ่งในสวนสาธารณะ",
  },
  {
    word: "Katze",
    example: "Die Katze schläft auf dem Sofa.",
    translation: "แมว",
    sentenceTranslation: "แมวหลับอยู่บนโซฟา",
  },
  {
    word: "Freude",
    example: "Ich empfinde große Freude.",
    translation: "ความสุข",
    sentenceTranslation: "ฉันรู้สึกมีความสุขมาก",
  },
];
